USE CUENTAHOGAR;

DROP TRIGGER IF EXISTS ACT_INS_CTAS;
DROP TRIGGER IF EXISTS ACT_UPD_CTAS;
DROP TRIGGER IF EXISTS ACT_DEL_CTAS;

DELIMITER |
    CREATE TRIGGER ACT_INS_CTAS
        AFTER INSERT ON MOVIMIENTOS
        FOR EACH ROW
        BEGIN
            UPDATE CUENTAS 
            SET CAPITAL = CAPITAL + NEW.IMPORTE 
            WHERE ID_CUENTA = NEW.ID_CUENTA_G;

            UPDATE CUENTAS 
            SET CAPITAL = CAPITAL - new.IMPORTE 
            WHERE ID_CUENTA = NEW.ID_CUENTA_I;
        END |
DELIMITER ;

DELIMITER |
    CREATE TRIGGER ACT_UPD_CTAS
        AFTER UPDATE ON MOVIMIENTOS
        FOR EACH ROW
        BEGIN
            UPDATE CUENTAS 
            SET CAPITAL = CAPITAL + NEW.IMPORTE
            WHERE ID_CUENTA = NEW.ID_CUENTA_G;

            UPDATE CUENTAS 
            SET CAPITAL = CAPITAL - OLD.IMPORTE
            WHERE ID_CUENTA = OLD.ID_CUENTA_G;

            UPDATE CUENTAS 
            SET CAPITAL = CAPITAL - NEW.IMPORTE
            WHERE ID_CUENTA = NEW.ID_CUENTA_I;

            UPDATE CUENTAS 
            SET CAPITAL = CAPITAL + OLD.IMPORTE
            WHERE ID_CUENTA = OLD.ID_CUENTA_I;
        END |
DELIMITER ;

DELIMITER |
    CREATE TRIGGER ACT_DEL_CTAS
        AFTER DELETE ON MOVIMIENTOS
        FOR EACH ROW
        BEGIN
            UPDATE CUENTAS 
            SET CAPITAL = CAPITAL - OLD.IMPORTE
            WHERE ID_CUENTA = OLD.ID_CUENTA_G;

            UPDATE CUENTAS 
            SET CAPITAL = CAPITAL + OLD.IMPORTE
            WHERE ID_CUENTA = OLD.ID_CUENTA_I;
        END |
DELIMITER ;